apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: tassawak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: tassawak/product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: tassawak-config
                  key: PORT_PRODUCT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: tassawak-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: tassawak-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: tassawak-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: tassawak-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tassawak-secrets
                  key: DB_PASSWORD
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: tassawak-config
                  key: KAFKA_BROKER
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 40
            periodSeconds: 20
